src/beans/Message.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
	private static final long serialVersionUID = 1L;
	
	private int Id;
	private String title;
	private String text;
	private String category;
	private Date createdDate;
	private int userId;
	private String name;
	public int getId() {
		return Id;
	}
	public void setId(int id) {
		Id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getCreated_date() {
		return createdDate;
	}
	public void setCreated_date(Date created_Date) {
		this.createdDate = created_Date;
	}
	public int getUser_id() {
		return userId;
	}
	public void setUser_id(int user_Id) {
		this.userId = user_Id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.Comment;
import beans.Message;
import service.CommentService;
import service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

			String searchCategory = request.getParameter("searchCategory");
			String startDate = request.getParameter("startDate");
			String endDate = request.getParameter("endDate");

			HttpSession session = request.getSession();
			List<String> errorMessages = new ArrayList<String>();

			// 投稿一覧のリスト
			List<Message> messages = new MessageService().getMessage(searchCategory, startDate, endDate);
			request.setAttribute("messages", messages);
			// コメント一覧のリスト
			List<Comment> comments = new CommentService().getComment();
			request.setAttribute("comments", comments);

			if(messages.size() == 0) {
				errorMessages.add("検索結果は０件です");
				session.setAttribute("errorMessages", errorMessages);
				session.setAttribute("searchCategory", searchCategory);
				request.getRequestDispatcher("/home.jsp").forward(request, response);
			}


			if(searchCategory != null ) {
				if(searchCategory.length() > 10) {
					errorMessages.add("カテゴリーは１０文字以下で入力してください");
					session.setAttribute("errorMessages", errorMessages);
					session.setAttribute("searchCategory", searchCategory);
					request.getRequestDispatcher("/home.jsp").forward(request, response);
				}
			}
			session.setAttribute("startDate", startDate);
			session.setAttribute("endDate", endDate);
			session.setAttribute("searchCategory", searchCategory);
			request.getRequestDispatcher("/home.jsp").forward(request, response);
	}
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;


@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		request.getRequestDispatcher("/login.jsp").forward(request, response);
	}
	
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		
		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");
		
		LoginService loginService = new LoginService();
		User user = loginService.login(login_id, password);
		
		HttpSession session = request.getSession();
		if (user != null) {
			
			session.setAttribute("loginUser", user);
			
			response.sendRedirect("./");
		} else {
			
			List<String> messages = new ArrayList<String>();
			session.setAttribute("login_id", login_id);
			
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			
			response.sendRedirect("login");
		}
	
	}
}

src/controller/MessageServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Message;
import beans.User;
import service.MessageService;

@WebServlet(urlPatterns = { "/message" })
public class MessageServlet extends HttpServlet {
	public static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		request.getRequestDispatcher("/message.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();

		if (isValid(request, messages)  == true) {

			User user = (User) session.getAttribute("loginUser");

			Message message = new Message();
			message.setTitle(request.getParameter("title"));
			message.setText(request.getParameter("text"));
			message.setCategory(request.getParameter("category"));
			message.setUser_id(user.getId());

			new MessageService().register(message);

			response.sendRedirect("./");
		} else {
			String title = request.getParameter("title");
			String category = request.getParameter("category");
			String text = request.getParameter("text");
			session.setAttribute("title", title);
			session.setAttribute("category", category);
			session.setAttribute("text", text);

			session.setAttribute("errorMessages", messages);
			response.sendRedirect("message");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String title = request.getParameter("title");
		String text = request.getParameter("text");
		String category = request.getParameter("category");

		if(StringUtils.isBlank(title) == true) {
			messages.add("タイトルを入力してください");
		} else {
			if(30 < title.length()) {
				messages.add("タイトルは30文字以下で入力して下さい");
			}
		}
		if(StringUtils.isBlank(category)) {
			messages.add("カテゴリーを入力してください");
		} else {
			if(10 < category.length()) {
				messages.add("カテゴリーは10文字以下で入力して下さい");
			}
		}
		if(StringUtils.isBlank(text)) {
			messages.add("テキストを入力してください");
		} else {
			if(1000 < text.length()) {
				messages.add("テキストは1000文字以下で入力して下さい");
			}
		}
		if(messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/UserEditServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Position;
import beans.Store;
import beans.User;
import service.PositionService;
import service.StoreService;
import service.UserService;

@WebServlet(urlPatterns = { "/useredit" })
public class UserEditServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		
		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		
		if(isValid(request, messages) == true) {
			
			int editUserId = Integer.parseInt(request.getParameter("empied"));
			User editUser = new UserService().getUser(editUserId);	
			
			List<Store> stores = new StoreService().getStore();
			request.setAttribute("stores", stores);
			List<Position> positions = new PositionService().getPosition();
			request.setAttribute("positions", positions);
			
			request.setAttribute("editUser", editUser);
			
			request.getRequestDispatcher("useredit.jsp").forward(request, response);
		} else {
			session.setAttribute("errorMessages", messages);
			
			response.sendRedirect("usersetting");
		}
	}
	
	private boolean isValid(HttpServletRequest request, List<String> messages) {
			
		
		if(StringUtils.isBlank(request.getParameter("empied"))) {
			messages.add("不正なアクセスです");
		} else if(request.getParameter("empied").matches("^\\D+$")) {
			messages.add("不正なアクセスです");
		} else {
			
			int editUserId = Integer.parseInt(request.getParameter("empied"));
			User editUser = new UserService().getUser(editUserId);	
			if(editUser == null) {
			messages.add("指定されたユーザーは無効です");
			} 
		}
		
		if(messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
	
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		
		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		
		if(isValid2(request, messages) == true) {
			
			User editUser = new User();
			editUser.setId(Integer.parseInt(request.getParameter("id")));
			editUser.setLogin_id(request.getParameter("login_id"));
			editUser.setPassword(request.getParameter("password"));
			editUser.setName(request.getParameter("name"));
			editUser.setStore_id(Integer.parseInt(request.getParameter("store_id")));
			editUser.setPosition_id(Integer.parseInt(request.getParameter("position_id")));
		
			new UserService().update(editUser);
		
			response.sendRedirect("usersetting");
		} else {
			
			User editUser = new User();
			editUser.setId(Integer.parseInt(request.getParameter("id")));
			editUser.setLogin_id(request.getParameter("login_id"));
			editUser.setPassword(request.getParameter("password"));
			editUser.setName(request.getParameter("name"));
			editUser.setStore_id(Integer.parseInt(request.getParameter("store_id")));
			editUser.setPosition_id(Integer.parseInt(request.getParameter("position_id")));
			
			List<Store> stores = new StoreService().getStore();
			session.setAttribute("stores", stores);
			List<Position> positions = new PositionService().getPosition();
			session.setAttribute("positions", positions);
			
			session.setAttribute("errorMessages", messages);
			session.setAttribute("editUser", editUser);
			response.sendRedirect("useredit.jsp");
		}
	}
	
	private boolean isValid2(HttpServletRequest request, List<String> messages) {
		
		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");
		String passwordConfirm = request.getParameter("passwordConfirm");
		String name = request.getParameter("name");
		int store_id = Integer.parseInt(request.getParameter("store_id"));
		int position_id = Integer.parseInt(request.getParameter("position_id"));
		
		User user2 = new UserService().getUser(Integer.parseInt(request.getParameter("id")));
		
		User existUser = new UserService().getExistUser(login_id);
		
		System.out.println(user2.getLogin_id());
		
		if(StringUtils.isBlank(login_id) == true) {
			messages.add("ログインIDを入力してください");
		} else if(login_id.length() < 6 || login_id.length() > 20) {
			messages.add("ログインIDは６文字以上２０文字以下で入力してください");
		} else if(!login_id.matches("^[A-Za-z0-9]+$")) {
			messages.add("ログインIDは半角英数字で入力してください");
		} else if(!(login_id.equals(user2.getLogin_id()))) {
					if(login_id.equals(existUser.getLogin_id())) {
						messages.add("そのログインIDは使用できません");
					} 
		}
					
		if(!(StringUtils.isBlank(password)) && !(StringUtils.isBlank(passwordConfirm))) {
			if(!(password.equals(passwordConfirm))) {
				messages.add("パスワードとパスワード(確認用）が一致しません");
			} else if(password.matches("^\\D+$") || !(password.matches("^.{6,20}$"))) {
				messages.add("パスワードは６文字以上２０文字以下の半角英数字記号で入力してください");
			}
		}
		
		if(!(password.equals(passwordConfirm))) {
			messages.add("パスワードとパスワード(確認用）が一致しません");
		} 
				
		if(StringUtils.isBlank(name) == true) {
			messages.add("名前を入力してください");
		} else if(name.length() > 10) {
			messages.add("名前は１０文字以下で入力してください");
		}
		
		if(store_id == 1 && position_id == 2) {
			messages.add("支店と部署の組み合わせが無効です");
		}
		if(store_id != 1 && position_id == 1) {
			messages.add("支店と部署の組み合わせが無効です");
		}
		
		if(messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/UserRegisterServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Position;
import beans.Store;
import beans.User;
import service.PositionService;
import service.StoreService;
import service.UserService;

@WebServlet(urlPatterns = { "/userregister" })
public class UserRegisterServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	@Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
			
		List<Store> stores = new StoreService().getStore();
		request.setAttribute("stores", stores);
		List<Position> positions = new PositionService().getPosition();
		request.setAttribute("positions", positions);
		
        request.getRequestDispatcher("userregister.jsp").forward(request, response);
    }
	
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException { 
		
		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		
		User user = new User();
		user.setLogin_id(request.getParameter("login_id"));
		user.setPassword(request.getParameter("password"));
		user.setName(request.getParameter("name"));
		user.setStore_id(Integer.parseInt(request.getParameter("store_id")));
		user.setPosition_id(Integer.parseInt(request.getParameter("position_id")));
		
		if(isValid(request, messages) == true) {
			
			new UserService().register(user);
			
			response.sendRedirect("./");
		} else {
			session.setAttribute("errorMessages", messages);
			session.setAttribute("user", user);
	
			response.sendRedirect("userregister");
		}
	}
	
	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");
		String passwordConfirm = request.getParameter("passwordConfirm");
		String name = request.getParameter("name");
		int store_id = Integer.parseInt(request.getParameter("store_id"));
		int position_id = Integer.parseInt(request.getParameter("position_id"));
		
		User existUser = new UserService().getExistUser(login_id);
		
		
		if(StringUtils.isBlank(login_id) == true) {
			messages.add("ログインIDを入力してください");
		} else if(login_id.length() < 6 || login_id.length() > 20) {
			messages.add("ログインIDは６文字以上２０文字以下で入力してください");
		} else if(!login_id.matches("^[A-Za-z0-9]+$")) {
			messages.add("ログインIDは半角英数字で入力してください");
		} else if(existUser != null) {
				if(login_id.equals(existUser.getLogin_id())) {
				messages.add("そのログインIDは使用できません");
			}
		}
			
		if(StringUtils.isBlank(password) == true) {
			messages.add("パスワードを入力してください");
		} else if(!(password.equals(passwordConfirm))) {
			messages.add("パスワードとパスワード(確認用）が一致しません");
		} else if(password.matches("^\\D+$") || !(password.matches("^.{6,20}$"))) {
			messages.add("パスワードは６文字以上２０文字以下の半角英数字記号で入力してください");
		} 
		
		if(StringUtils.isBlank(name) == true) {
			messages.add("名前を入力して下さい");
		} else if(name.length() > 10) {
			messages.add("名前は１０文字以下で入力してください"); 
		}
		
		if(store_id == 1 && position_id == 2) {
			messages.add("支店と部署の組み合わせが無効です");
		}
		if(store_id != 1 && position_id == 1) {
			messages.add("支店と部署の組み合わせが無効です");
		}
		if(messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
	
}

src/controller/UserSettingServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns ="/usersetting")
public class UserSettingServlet extends HttpServlet {
	public static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		
		List<User> users =new UserService().getUsers();
		
		request.setAttribute("users", users);
		request.getRequestDispatcher("/usersetting.jsp").forward(request, response);
	}
}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false" %>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title>ホーム画面</title>
            <link href="./CSS/homestyle.css" rel="stylesheet" type="text/css">
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        </head>
    <body>
       <h1>HOME</h1>
        <div class="main-contents">
            <div class="header">
                    <a href="message" class="message">新規投稿</a> <br/>
                    <c:if test="${ loginUser.position_id == 1 }" >
                       <a href="usersetting" class="usersetting">ユーザー管理</a> <br />
                    </c:if>
                    <form action="./" method="get">
                       <label for="searchCategory" >カテゴリ検索</label> <br />
                       <input type="text" name="searchCategory" value="${searchCategory}" class="searchCategory"/> <br />

                       <label for="dateSearch" >投稿日検索</label> <br />
                       <input type="date" name="startDate" value="${startDate}" class="startDate" /> <br />
                       <input type="date" name="endDate" value="${endDate}" class="endDate" /> <br />
                       <input type="submit" value="検索" class="search" />
                    </form> <br />
                       <a href="./" class="reset">リセット</a>
            </div>
            <a href="logout" class="logout">ログアウト</a>
            <c:remove var="searchCategory" scope="session" />
            <br />

        <div class="messages">
        <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </li>
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
          </c:if>
            <c:forEach items="${messages}" var="message">
                <div class="message">
                    <div class="title"><c:out value="${message.title}" /></div> <br />
                    <div class="category"><c:out value="${message.category}" /></div> <br />
                    <div class="text"><c:forEach var="str" items="${fn:split(message.text, '
                                      ')}"><c:out value="${str}" /><br /></c:forEach> </div>
                    <div class="date"><fmt:formatDate value="${message.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
                    <div class="name"><c:out value="${message.name}" /></div>
                </div>
                    <%-- 投稿の削除 --%>
                <div class="messageDelete">
                    <c:if test="${ message.user_id == loginUser.id }" >
                       <form action="messageDelete" method="post" >
                            <input type="hidden" name="message.id" value="${message.id}" />
                            <input type="submit" value="投稿の削除" onClick="return confirm('本当に削除しますか？')" class="submit" />
                       </form>
                    </c:if>
                    <br />
                </div>
                <div class="comments">
                    <%-- メッセージのIDに対応するコメントの表示 --%>
                    <c:forEach items="${comments}" var="comment">
                       <c:if test="${ message.id == comment.messageId }" >
                               <span class="name"> <c:out value="${comment.name}" /> </span> <br />
                               <span class="text"> <c:forEach var="str" items="${fn:split(comment.text,'
                                                   ')}"><c:out value="${str}" /><br /></c:forEach></span>
                               <span class="created_date"> <fmt:formatDate value="${ comment.created_date }" pattern="yyyy/MM/dd HH:mm:ss" /></span>

                               <div class="commentDelete">
                                   <%-- コメントの削除 --%>
                                   <c:if test="${ comment.userId == loginUser.id }" >
                                        <form action="commentDelete" method="post" >
                                          <input type="hidden" name="comment.id" value="${comment.id}" />
                                          <input type="submit" value="コメントの削除" onClick="return confirm('本当に削除しますか？')" class="submit" />
                                        </form>
                                   </c:if>
                                   <br />
                               </div>
                       </c:if>
                    </c:forEach>
                </div>
                    <br />
                <div class="comment">
                    <%-- コメントの書き込みフォーム --%>
                    <form action="comment" method="post">
                       <input type="hidden" name="message.id" value="${message.id}" />
                       <textarea name="text" cols="100" rows="5" id="text"><c:if test="${message.id == commentMessageId}">${comment}</c:if></textarea> <br />
                       <input type="submit" value="コメント" class="submit"/> <br />
                       <br />
                    </form>
                </div>

            </c:forEach>
        </div>
          <c:remove var="comment" scope="session" />
          <c:remove var="commentMessageId" scope="session" />
        </div>
    </body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c"	uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン画面</title>
		<link href="./CSS/loginstyle.css" rel="stylesheet" type="text/css">
	</head>
	<body>	
		<div class="main-contents">
			<c:if test="${ not empty errorMessages }"> 
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}"/>
						</li>
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>
			
			<form action="login" method="post"><br />
				<div class="login_id">
				<label for="login_id" >ログインID</label>
				<input name="login_id" value="${login_id}" id="login_id" class="login_id"/> <br />
				</div> 
				
                <div class="password">
				<label for="password" >パスワード</label>
				<input name="password" type="password" value="${password}" id="password" class="password"/> <br />
				</div> <br />
				
				
				<input type="submit" value="ログイン" class="submit"/> <br />
			</form>
		</div>
	   <c:remove var="login_id" scope="session"/>
	</body>
</html>

WebContent/message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>新規投稿画面</title>
        <link href="./CSS/messagestyle.css" rel="stylesheet" type="text/css">
    </head>
    <body>
       <h1>新規投稿</h1>
       <div class="main-contents">
          <c:if test="${ not empty errorMessages }">
              <div class="errorMessages">
                  <ul>
                      <c:forEach items="${errorMessages}" var="message">
                          <li><c:out value="${message}" />
                      </c:forEach>
                  </ul>
              </div>
              <c:remove var="errorMessages" scope="session"/>
          </c:if>
          <div class="message" >
              <form action="message" method="post">

                 <div class="title" >
                 <label for="title">タイトル（３０文字以内）</label> <br />
                 <input type="text" name="title" value="${title}" class="title" /> <br />
                 </div>

                 <div class="category" >
                 <label for="category">カテゴリー（１０文字以内）</label> <br />
                 <input type="text" name="category" value="${category}" class="category" /> <br />
                 </div>

                 <div class="text" >
                 <label for="text">テキスト（１０００文字以内）</label> <br />
                 <textarea name="text" cols="100" rows="10" id="text" class="text" >${text}</textarea> <br />
                 </div>

                 <input type="submit" value="投稿" class="submit" /> <br />
                 <a href="./" class="return">戻る</a>
              </form>
          </div>
          <c:remove var="title" scope="session"/>
          <c:remove var="category" scope="session"/>
          <c:remove var="text" scope="session"/>
       </div>

</body>
</html>